version: '3.7'

services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1  # Для немедленного вывода логов
      - FLASK_ENV=development  # Добавляем для более подробных логов
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1  # Отключаем кэширование .pyc файлов
      - PYTORCH_NO_CUDA=1
      - OMP_NUM_THREADS=1
      - WHISPER_BATCH_SIZE=1
    volumes:
      - app_videos:/app/videos
      - app_output:/app/output
      - app_temp:/app/temp
      - app_cache:/app/cache/models
      - ${PWD}/client_secrets.json:/app/client_secrets.json:ro
      - ${PWD}/api.txt:/app/api.txt:ro
    restart: unless-stopped
    mem_limit: 384m
    mem_reservation: 256m
    working_dir: /app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    ulimits:
      nofile:
        soft: 32768
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 384M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  app_videos:
  app_output:
  app_temp:
  app_cache:
