version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"  # Хост:Контейнер
    environment:
      - PORT=5000
    volumes:
      - ./output:/app/output  # Сохраняем результаты