version: '3.7'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./videos:/app/videos
      - ./output:/app/output
      - ./temp:/app/temp
      - ./logs:/app/logs
      - ./client_secrets.json:/app/client_secrets.json:ro
      - ./api.txt:/app/api.txt:ro
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=src.server
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: gunicorn --workers=2 --threads=4 --bind 0.0.0.0:8080 src.server:app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis
    networks:
      - app_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 384M
        reservations:
          cpus: '0.2'
          memory: 256M

  worker:
    build: .
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./videos:/app/videos
      - ./output:/app/output
      - ./temp:/app/temp
      - ./logs:/app/logs
      - ./client_secrets.json:/app/client_secrets.json:ro
      - ./api.txt:/app/api.txt:ro
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery -A src.server.celery worker --loglevel=info
    depends_on:
      - redis
    networks:
      - app_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 384M
        reservations:
          cpus: '0.2'
          memory: 256M

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
