version: '3.8'

services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - ./videos:/app/videos
      - ./output:/app/output
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./cache:/app/cache
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.server.celery worker --loglevel=info
    volumes:
      - ./config:/app/config
      - ./videos:/app/videos
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge