version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 128M

  server:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python -m gunicorn src.server:app --bind 0.0.0.0:8080 --workers 1 --threads 2
    ports:
      - "8080:8080"
    volumes:
      - ./videos:/app/videos
      - ./output:/app/output
      - ./temp:/app/temp
      - ./cache:/app/cache
      - ./logs:/app/logs
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  worker:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A src.server:celery worker --loglevel=info
    volumes:
      - ./videos:/app/videos
      - ./output:/app/output
      - ./temp:/app/temp
      - ./cache:/app/cache
      - ./logs:/app/logs
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
