version: '3.7'

services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: always
    mem_limit: 400m  # Увеличил лимит памяти для стабильности
    mem_reservation: 256m
