version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # Изменено на 8080
    environment:
      - PORT=8080
    volumes:
      - ./output:/app/output  # Сохраняем результаты
      - ./cache:/app/cache
      - ./torch:/app/torch
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 200M
    restart: unless-stopped
