version: '3.7'

services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1  # Для немедленного вывода логов
      - FLASK_ENV=development  # Добавляем для более подробных логов
      - FLASK_DEBUG=1
    volumes:
      - app_videos:/app/videos
      - app_output:/app/output
      - app_temp:/app/temp
      - app_cache:/app/cache/models
      - ./client_secrets.json:/app/client_secrets.json:ro
      - ./api.txt:/app/api.txt:ro
    restart: unless-stopped  # Изменяем политику перезапуска
    mem_limit: 1024m  # Увеличиваем лимит памяти
    mem_reservation: 512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  app_videos:
  app_output:
  app_temp:
  app_cache:
