version: '3.7'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    mem_limit: 256m
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    networks:
      - app_network

  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1  # Для немедленного вывода логов
      - FLASK_ENV=development  # Добавляем для более подробных логов
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1  # Отключаем кэширование .pyc файлов
      - PYTORCH_NO_CUDA=1
      - OMP_NUM_THREADS=1
      - WHISPER_BATCH_SIZE=1
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - app_videos:/app/videos
      - app_output:/app/output
      - app_temp:/app/temp
      - app_cache:/app/cache/models
      - ${PWD}/client_secrets.json:/app/client_secrets.json:ro
      - ${PWD}/api.txt:/app/api.txt:ro
    restart: unless-stopped
    mem_reservation: 1024m
    working_dir: /app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    ulimits:
      nofile:
        soft: 32768
        hard: 65536
    depends_on:
      - redis
    networks:
      - app_network
    mem_limit: 512m
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  worker:
    build: .
    command: celery -A src.server.celery worker --loglevel=info --pool=solo
    volumes:
      - app_videos:/app/videos
      - app_output:/app/output
      - app_temp:/app/temp
      - app_cache:/app/cache/models
      - ${PWD}/client_secrets.json:/app/client_secrets.json:ro
      - ${PWD}/api.txt:/app/api.txt:ro
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
      - C_FORCE_ROOT=true
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    mem_limit: 512m
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - app_network

volumes:
  app_videos:
  app_output:
  app_temp:
  app_cache:
  redis_data:

networks:
  app_network:
    driver: bridge
