version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app/src
    volumes:
      - ./output:/app/output
      - ./cache:/app/cache
      - ./torch:/app/torch
      - ./config.yaml:/app/config.yaml  # Правильное монтирование файла
    command: gunicorn --bind 0.0.0.0:8080 main:app
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./output:/app/output
      - ./cache:/app/cache
      - ./torch:/app/torch
      - ./config.yaml:/app/config.yaml  # Правильное монтирование файла
    depends_on:
      - redis
    restart: unless-stopped
