version: '3.7'

services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - app_videos:/app/videos
      - app_output:/app/output
      - app_temp:/app/temp
      - app_cache:/app/cache/models
    restart: always
    mem_limit: 512m  # Увеличил лимит памяти еще больше
    mem_reservation: 256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  app_videos:
  app_output:
  app_temp:
  app_cache:
