global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'youtube_converter'
    static_configs:
      - targets: ['server:8080']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scheme: 'http'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml" 