global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'youtube-converter'
    static_configs:
      - targets: ['server:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379'] 