# config/config.yaml
temp_dir: '/app/temp'
output_dir: '/app/output'
video_dir: '/app/videos'

# Директория кеша для моделей
model_cache: "/app/cache/models"

memory:
  max_video_size: 50  # MB
  chunk_size: 1  # MB
  cleanup_interval: 3600  # seconds
  emergency_cleanup_threshold: 85  # percent

transcription:
  model: 'tiny'  # tiny, base, small, medium, large
  use_gpu: false
  batch_size: 1
  chunk_duration: 30  # seconds

video_processing:
  max_frames: 20
  frame_mode: 'scenes'
  frame_interval: 60  # seconds
  max_resolution: 720
  frame_quality: 85
  thumbnail_size: [320, 180]

blip:
  enabled: false  # Отключаем генерацию описаний кадров через BLIP
  model: 'Salesforce/blip-image-captioning-base'
  max_length: 50

parallel_processing:
  enabled: false
  max_workers: 1
  queue_size: 2

server:
  host: "0.0.0.0"
  port: 8080
  workers: 2
  threads: 4
  timeout: 120

redis:
  url: "redis://redis:6379/0"
  max_connections: 10
  socket_timeout: 5

celery:
  concurrency: 2
  task_timeout: 3600
  max_retries: 3
  retry_delay: 300

youtube_api:
  credentials_file: "client_secrets.json"
  token_file: "token.pickle"
  scopes: 
    - "https://www.googleapis.com/auth/youtube.readonly"

network:
  timeout: 300  # seconds
  retries: 3
  retry_delay: 5  # seconds

storage:
  video_max_size: 500  # MB
  cleanup_interval: 3600  # seconds
  temp_file_ttl: 86400  # seconds (24 hours)
  max_file_age: 3600  # 1 час
  temp_dir: "/app/temp"
  output_dir: "/app/output"
  video_dir: "/app/videos"
  cache_dir: "/app/cache"
  temp_lifetime: 3600  # Время жизни временных файлов (1 час)
  cache_size_mb: 1000  # Ограничение кэша в 1GB
  emergency_cleanup_threshold: 85  # процент заполнения
  max_video_size_mb: 500
  max_temp_size_gb: 2

pdf:
  template: 'default'
  max_size: 50  # MB
  compression: 'medium'  # low, medium, high
  image_quality: 85
  dpi: 150

processing:
  max_frames: 20
  audio_format: "wav"
  video_format: "mp4"
  pdf_quality: "high"
  frame_interval: 10
  image_quality: 60
  image_max_width: 800
  thumbnail_size: [320, 180]
  max_resolution: 720

monitoring:
  enabled: true
  prometheus_port: 9090
  metrics:
    request_timeout: 30
    slow_request_threshold: 10
    error_threshold: 50
  metrics_interval: 15
  log_level: 'INFO'

video:
  max_resolution: 480  # Ограничиваем качество видео
  max_size_mb: 500    # Максимальный размер видео
  cleanup_delay: 300  # Удаление через 5 минут после создания PDF

whisper:
  model: 'tiny'
  device: 'cpu'
  batch_size: 16
  compute_type: 'int8'

cleanup:
  temp_lifetime: 3600
  cache_size_mb: 1000
