# config/config.yaml
temp_dir: "/app/temp/"  # Директория для временных файлов
output_dir: "/app/output/"  # Директория для результатов

# Директория кеша для моделей
model_cache: "/app/cache/models"

transcription:
  model: "medium"  # Модель Whisper (base, small, medium)
  use_gpu: false  # Whisper работает на CPU (сервер слабый)

video_processing:
  max_frames: 20  # Максимальное число кадров
  frame_mode: "interval"  # Режим выбора кадров (scenes или interval)
  frame_interval: 30  # Интервал в секундах (для режима interval)

blip:
  enabled: false  # Отключаем генерацию описаний кадров через BLIP

parallel_processing:
  enabled: false  # Отключаем параллельную обработку видео и аудио (слабый сервер)
  max_workers: 1  # Только 1 поток (экономим ресурсы)

server:
  host: "0.0.0.0"
  port: 8080

youtube_api:
  credentials_file: "client_secrets.json"
  token_file: "token.pickle"
  scopes: 
    - "https://www.googleapis.com/auth/youtube.readonly"

network:
  timeout: 300  # Таймаут для сетевых запросов
  retries: 3    # Количество попыток

storage:
  cleanup_interval: 3600  # Интервал очистки временных файлов
  max_file_age: 86400    # Максимальное время хранения файлов
