# config/config.yaml
temp_dir: "temp/"  # Директория для временных файлов
output_dir: "output/"  # Директория для результатов

transcription:
  model: "base"  # Модель Whisper (base, small, medium)
  use_gpu: true  # Использовать GPU для транскрибации

video_processing:
  max_frames: 50  # Максимальное число кадров
  frame_mode: "interval"  # Режим выбора кадров (scenes или interval)
  frame_interval: 30  # Интервал в секундах (для режима interval)

blip:
  enabled: false  # Включить генерацию описаний кадров через BLIP

parallel_processing:
  enabled: true  # Включить параллельную обработку видео и аудио
  max_workers: 2  # Количество потоков (можно увеличить на мощных серверах)

celery:
  enabled: true  # Включить Celery для фоновой обработки
  broker_url: "redis://redis:6379/0"
  backend_url: "redis://redis:6379/0"

