# config/config.yaml
temp_dir: "/app/temp/"
output_dir: "/app/output/"

# Директория кеша для моделей
model_cache: "/app/cache/models"

transcription:
  model: "tiny"  # ⬅️ Меняем с "base" на "tiny", чтобы уменьшить RAM
  use_gpu: false
  whisper_cache: false

video_processing:
  max_frames: 3  # ⬅️ Снижаем нагрузку, уменьшив количество кадров
  frame_mode: "interval"
  frame_interval: 30

blip:
  enabled: false

parallel_processing:
  enabled: true
  max_workers: 1  # Ограничиваем число потоков

celery:
  enabled: true
  broker_url: "redis://redis:6379/0"
  backend_url: "redis://redis:6379/0"
