# config/config.yaml
temp_dir: '/app/temp'
output_dir: '/app/output'
video_dir: '/app/videos'

# Директория кеша для моделей
model_cache: "/app/cache/models"

memory:
  max_video_size: 50
  chunk_size: 1
  cleanup_interval: 30
  emergency_cleanup_threshold: 85

transcription:
  model: 'tiny'
  use_gpu: false
  batch_size: 1
  chunk_duration: 30

video_processing:
  max_frames: 10
  frame_mode: 'interval'
  frame_interval: 60
  max_resolution: '720p'

blip:
  enabled: false  # Отключаем генерацию описаний кадров через BLIP

parallel_processing:
  enabled: false
  max_workers: 1
  queue_size: 2

server:
  host: "0.0.0.0"
  port: 8080

youtube_api:
  credentials_file: "client_secrets.json"
  token_file: "token.pickle"
  scopes: 
    - "https://www.googleapis.com/auth/youtube.readonly"

network:
  timeout: 300  # Таймаут для сетевых запросов
  retries: 3    # Количество попыток

storage:
  cleanup_interval: 3600  # Интервал очистки временных файлов
  max_file_age: 86400    # Максимальное время хранения файлов

pdf:
  template: 'default'
  max_size: 50  # MB
