# config/config.yaml
temp_dir: "/app/temp/"
output_dir: "/app/output/"

# Директория кеша для моделей
model_cache: "/app/cache/models"

transcription:
  model: "base"  # Минимальная модель Whisper
  use_gpu: false
  whisper_cache: false  # Отключаем кеширование моделей Whisper

video_processing:
  max_frames: 5  # Уменьшаем число кадров, чтобы снизить нагрузку
  frame_mode: "interval"
  frame_interval: 30

blip:
  enabled: false  # Отключаем BLIP для уменьшения нагрузки

parallel_processing:
  enabled: true
  max_workers: 1  # Ограничиваем число потоков

celery:
  enabled: true
  broker_url: "redis://redis:6379/0"
  backend_url: "redis://redis:6379/0"

