version: 1
disable_existing_loggers: false

formatters:
    standard:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout

    file:
        class: logging.FileHandler
        level: INFO
        formatter: standard
        filename: /app/logs/app.log
        mode: a

root:
    level: INFO
    handlers: [console, file]
    propagate: yes

loggers:
    youtube_api:
        level: INFO
        handlers: [console, file]
        propagate: false
    
    process_video:
        level: INFO
        handlers: [console, file]
        propagate: false
    
    frame_processor:
        level: INFO
        handlers: [console, file]
        propagate: false
    
    audio_extractor:
        level: INFO
        handlers: [console, file]
        propagate: false
    
    output_generator:
        level: INFO
        handlers: [console, file]
        propagate: false
    
    local_processing:
        level: INFO
        handlers: [console, file]
        propagate: false 