version: 1
disable_existing_loggers: false

formatters:
    default:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: default
        stream: ext://sys.stdout

    file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: default
        filename: /app/logs/app.log
        maxBytes: 10485760  # 10MB
        backupCount: 5
        encoding: utf8

    error_file:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: default
        filename: /app/logs/error.log
        maxBytes: 10485760  # 10MB
        backupCount: 5
        encoding: utf8

loggers:
    root:
        level: INFO
        handlers: [console, file, error_file]

    youtube_api:
        level: INFO
        handlers: [console, file, error_file]
        propagate: false
    
    frame_processor:
        level: INFO
        handlers: [console, file, error_file]
        propagate: false
    
    audio_extractor:
        level: INFO
        handlers: [console, file, error_file]
        propagate: false
    
    output_generator:
        level: INFO
        handlers: [console, file, error_file]
        propagate: false
    
    server:
        level: INFO
        handlers: [console, file, error_file]
        propagate: false 