name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Verify project files
        run: |
          # Проверка наличия основных файлов
          required_files=(
            "start.sh"
            "requirements.txt"
            "README.md"
            "Procfile"
            "Dockerfile"
            "docker-compose.yml"
            ".dockerignore"
            ".env"
            "templates/index.html"
            "systemd/youtube-converter.service"
            "static/js/main.js"
            "src/youtube_api.py"
            "src/server.py"
            "src/process_video.py"
            "src/output_generator.py"
            "src/frame_processor.py"
            "src/audio_extractor.py"
            "src/__init__.py"
            "prometheus/prometheus.yml"
            "config/youtube.cookies"
            "config/logging.yaml"
            "config/config.yaml"
          )

          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Error: Required file $file is missing"
              exit 1
            fi
          done

          # Проверка прав на исполнение
          chmod +x start.sh

          # Проверка Dockerfile
          if ! grep -q "FROM python:3.9-slim" Dockerfile; then
            echo "Error: Invalid Dockerfile base image"
            exit 1
          fi

      - name: Verify secrets
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_CLIENT_SECRETS: ${{ secrets.YOUTUBE_CLIENT_SECRETS }}
        run: |
          for var in SSH_HOST SSH_USER SSH_PRIVATE_KEY YOUTUBE_API_KEY YOUTUBE_CLIENT_SECRETS; do
            if [ -z "${!var}" ]; then
              echo "Error: $var is not set"
              exit 1
            fi
          done

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/youtube-converter
            
            # Создаем бэкап текущих данных
            timestamp=$(date +%Y%m%d_%H%M%S)
            mkdir -p backups
            tar -czf backups/data_$timestamp.tar.gz videos output logs || true
            
            # Клонируем свежую версию из репозитория
            git fetch origin main
            git reset --hard origin/main
            
            # Проверяем содержимое конфигурационных файлов
            echo "Checking config files..."
            for file in config/logging.yaml config/config.yaml; do
              if [ ! -s "$file" ]; then
                echo "Error: $file is empty"
                cat "$file"
                exit 1
              fi
            done
            
            # Проверяем структуру logging.yaml
            if ! grep -q "version: 1" config/logging.yaml; then
              echo "Error: Invalid logging.yaml structure"
              cat config/logging.yaml
              exit 1
            fi
            
            # Проверяем наличие всех необходимых файлов
            required_files=(
              "docker-compose.yml"
              "Dockerfile"
              "requirements.txt"
              "start.sh"
              "Procfile"
              "config/logging.yaml"
              "config/config.yaml"
              "config/youtube.cookies"
            )
            
            for file in "${required_files[@]}"; do
              if [ ! -f "$file" ]; then
                echo "Error: $file not found"
                exit 1
              fi
            done
            
            # Обновляем только секретные значения в config.yaml
            sed -i "s|api_key:.*|api_key: ${{ secrets.YOUTUBE_API_KEY }}|g" config/config.yaml
            sed -i "s|client_secrets:.*|client_secrets: '${{ secrets.YOUTUBE_CLIENT_SECRETS }}'|g" config/config.yaml
            
            # Обновляем .env файл с добавлением настроек Celery и Redis
            cat > .env << 'EOL'
            YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}
            REDIS_URL=redis://redis:6379/0
            CELERY_BROKER_URL=redis://redis:6379/0
            CELERY_RESULT_BACKEND=redis://redis:6379/0
            CELERY_TASK_SERIALIZER=json
            CELERY_RESULT_SERIALIZER=json
            MAX_WORKERS=2
            WHISPER_MODEL=tiny
            MAX_VIDEO_SIZE=500
            EMERGENCY_CLEANUP_THRESHOLD=85
            PROMETHEUS_PORT=9090
            GRAFANA_ADMIN_PASSWORD=admin
            EOL
            
            # Очистка и перезапуск
            docker-compose down
            docker system prune -af --volumes
            docker-compose pull
            docker-compose up -d --build
            
            # Ждем запуска контейнеров и проверяем их статус
            echo "Waiting for containers to start..."
            sleep 45
            
            # Проверка статуса контейнеров
            if ! docker-compose ps | grep -q "Up"; then
              echo "Error: Containers failed to start"
              echo "Server logs:"
              docker-compose logs server
              echo "Worker logs:"
              docker-compose logs worker
              echo "Redis logs:"
              docker-compose logs redis
              exit 1
            fi
            
            # Проверка подключения к Redis
            if ! docker-compose exec -T redis redis-cli ping | grep -q "PONG"; then
              echo "Error: Redis is not responding"
              exit 1
            fi

      - name: Health checks
        run: |
          check_endpoint() {
            local url=$1
            local name=$2
            local max_attempts=10
            local wait_time=60
            
            echo "Checking $name..."
            for i in $(seq 1 $max_attempts); do
              echo "Attempt $i of $max_attempts"
              if curl -sSf "$url" >/dev/null 2>&1; then
                echo "$name check passed"
                return 0
              fi
              echo "Waiting ${wait_time}s before next attempt..."
              sleep $wait_time
            done
            echo "$name check failed after $max_attempts attempts"
            return 1
          }
          
          # Проверяем основной сервис и Redis
          check_endpoint "http://${{ secrets.SSH_HOST }}:8080/health" "API" || exit 1

      - name: Verify dependencies
        run: |
          # Проверяем requirements.txt
          echo "Checking requirements.txt..."
          if ! grep -q "google-auth" requirements.txt || \
             ! grep -q "flask" requirements.txt || \
             ! grep -q "celery" requirements.txt || \
             ! grep -q "redis" requirements.txt; then
            echo "Error: Missing core dependencies in requirements.txt"
            cat requirements.txt
            exit 1
          fi
          
          # Проверяем start.sh
          echo "Checking start.sh..."
          if ! grep -q "gunicorn" start.sh || \
             ! grep -q "mkdir -p /app/" start.sh; then
            echo "Error: Invalid start.sh structure"
            cat start.sh
            exit 1
          fi
          
          # Проверяем права на исполнение
          chmod +x start.sh

          # Устанавливаем права доступа
          chmod -R 755 config/
          chmod 644 config/*.yaml
          chmod 644 requirements.txt
          chmod 755 start.sh