name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Debug secrets
        run: |
          if [ -n "${{ secrets.SSH_HOST }}" ]; then
            echo "SSH_HOST is set"
          else
            echo "SSH_HOST is not set"
          fi
          if [ -n "${{ secrets.SSH_USER }}" ]; then
            echo "SSH_USER is set"
          else
            echo "SSH_USER is not set"
          fi
          if [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "SSH_PRIVATE_KEY is set"
          else
            echo "SSH_PRIVATE_KEY is not set"
          fi

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu

            # Проверяем, есть ли репозиторий, иначе клонируем
            if [ ! -d "youtube-converter/.git" ]; then
              git clone https://github.com/GeorgyKomkov/youtube-educational-converter.git youtube-converter
            fi

            cd youtube-converter
            git fetch --all
            git reset --hard origin/main

            echo "Stopping running containers..."
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -aq) || true
            docker network prune -f || true

            echo "Cleaning up Docker system..."
            docker system prune -af --volumes

            echo "Building and starting containers..."
            docker-compose build
            docker-compose up -d

            echo "Deployment completed successfully."
