name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Verify secrets
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_CLIENT_SECRETS: ${{ secrets.YOUTUBE_CLIENT_SECRETS }}
        run: |
          for var in SSH_HOST SSH_USER SSH_PRIVATE_KEY YOUTUBE_API_KEY YOUTUBE_CLIENT_SECRETS; do
            if [ -z "${!var}" ]; then
              echo "Error: $var is not set"
              exit 1
            fi
          done

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Создание пользователя
            id -u youtube-converter &>/dev/null || sudo useradd -m youtube-converter
            
            # Подготовка директории
            sudo mkdir -p /opt/youtube-converter
            cd /opt/youtube-converter
            
            # Сохранение важных файлов
            if [ -f ".env" ]; then
              cp .env .env.backup
            fi
            if [ -f "client_secrets.json" ]; then
              cp client_secrets.json client_secrets.json.backup
            fi
            
            # Очистка Docker
            docker-compose down || true
            docker system prune -af || true
            
            # Клонирование репозитория
            git clone https://github.com/GeorgyKomkov/youtube-educational-converter.git .
            
            # Восстановление файлов
            if [ -f ".env.backup" ]; then
              mv .env.backup .env
            else
              # Создание .env файла
              cat > .env << EOF
              YOUTUBE_API_KEY='${{ secrets.YOUTUBE_API_KEY }}'
              FLASK_ENV=production
              MAX_WORKERS=2
              WHISPER_MODEL=tiny
              EOF
            fi
            
            if [ -f "client_secrets.json.backup" ]; then
              mv client_secrets.json.backup client_secrets.json
            else
              echo '${{ secrets.YOUTUBE_CLIENT_SECRETS }}' > client_secrets.json
            fi
            
            # Создание директорий и установка прав
            mkdir -p videos output temp cache/models logs
            chmod -R 777 videos output temp cache logs
            
            # Запуск приложения
            docker-compose up -d --build
            
            # Проверка статуса
            sleep 30
            docker-compose ps
            
      - name: Health check
        run: |
          sleep 45
          for i in {1..3}; do
            if curl -f "http://${{ secrets.SSH_HOST }}:8080/health"; then
              exit 0
            fi
            sleep 15
          done
          exit 1

      - name: Verify Prometheus
        run: |
          sleep 15
          curl -f "http://${{ secrets.SSH_HOST }}:9091/metrics" || exit 1

      - name: Verify Grafana
        run: |
          sleep 15
          curl -f "http://${{ secrets.SSH_HOST }}:3000" || exit 1