name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Copy project files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/root/youtube-converter"
      
      - name: Deploy application
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/youtube-converter
            
            echo "Creating credentials files..."
            echo '${{ secrets.YOUTUBE_CLIENT_SECRETS }}' > client_secrets.json
            echo '${{ secrets.YOUTUBE_API_KEY }}' > api.txt
            chmod 644 client_secrets.json api.txt
            
            echo "Starting containers..."
            docker-compose down
            docker system prune -f
            docker-compose up -d
            
            echo "Waiting for container to initialize..."
            sleep 45
            
            echo "Docker logs:"
            docker-compose logs
            
            echo "Container status:"
            docker ps -a
            
            echo "Memory usage:"
            free -h
            
            echo "Disk space:"
            df -h

      - name: Verify deployment
        run: |
          sleep 120
          for i in {1..5}; do
            echo "Attempt $i: Checking server status..."
            if curl -v --fail --max-time 30 http://${{ secrets.SSH_HOST }}:8080/health; then
              echo "Service is up and running!"
              exit 0
            fi
            echo "Attempt $i failed, waiting..."
            sleep 45
          done
          echo "Service failed to start properly"
          exit 1
