name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Подготовка директории
            mkdir -p /root/youtube-converter
            cd /root/youtube-converter
            
            # Очистка Docker
            docker-compose down --volumes || true
            docker system prune -af --volumes || true
            
            # Копирование новых файлов
            rm -rf /root/youtube-converter/*
            
            # Клонирование репозитория
            git clone https://github.com/GeorgyKomkov/youtube-educational-converter.git .
            
            # Создание credentials
            echo '${{ secrets.YOUTUBE_CLIENT_SECRETS }}' > client_secrets.json
            echo '${{ secrets.YOUTUBE_API_KEY }}' > api.txt
            chmod 644 client_secrets.json api.txt
            
            # Создание директорий с правами
            mkdir -p videos output temp cache/models logs
            chmod -R 777 videos output temp cache logs
            
            # Запуск приложения
            docker-compose build --no-cache
            docker-compose up -d
            
            # Проверка статуса
            sleep 30
            docker-compose ps
            docker-compose logs

      - name: Health check
        run: |
          sleep 45
          curl -f "http://${{ secrets.SSH_HOST }}:8080/health" || exit 1