name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Debug secrets
        run: |
          if [ -n "${{ secrets.SSH_HOST }}" ]; then
            echo "SSH_HOST is set"
          else
            echo "SSH_HOST is not set"
          fi
          if [ -n "${{ secrets.SSH_USER }}" ]; then
            echo "SSH_USER is set"
          else
            echo "SSH_USER is not set"
          fi
          if [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "SSH_PRIVATE_KEY is set"
          else
            echo "SSH_PRIVATE_KEY is not set"
          fi

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/youtube-converter
            if [ ! -d .git ]; then
              git clone https://github.com/GeorgyKomkov/youtube-educational-converter.git .
            fi
            git fetch
            git reset --hard origin/main
            docker-compose down
            docker system prune -af --volumes
            docker-compose up -d --build
            
            # Добавляем задержку перед запуском Celery
            sleep 10
            docker-compose exec -d app celery -A celery_app worker --loglevel=info
