name: Deploy to Server

on:
  push:
    branches:
      - main  # Запуск при пуше в main
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        run: |
          docker build -t youtube-converter-app .
          docker tag youtube-converter-app your-dockerhub-username/youtube-converter-app:latest
          docker push your-dockerhub-username/youtube-converter-app:latest

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            cd /path/to/your/project  # Убедись, что здесь правильный путь до docker-compose.yml
            docker pull your-dockerhub-username/youtube-converter-app:latest
            docker-compose down
            docker-compose up -d
            exit
          EOF
