name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/youtube-converter
            if [ ! -d .git ]; then
              git clone https://github.com/GeorgyKomkov/youtube-educational-converter.git .
            fi
            git fetch
            git reset --hard origin/main
            docker-compose down
            docker system prune -af --volumes
            docker-compose up -d --build