name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create required directories
        run: |
          mkdir -p videos output temp cache/models logs
          chmod -R 777 videos output temp cache logs
      
      - name: Build and start containers
        run: |
          docker-compose build
          docker-compose up -d
      
      - name: Check container status
        run: |
          docker-compose ps
          docker-compose logs server
      
      - name: Health check
        run: |
          sleep 10
          curl -f http://localhost:8080/health || (docker-compose logs && exit 1)

      - name: Setup environment
        run: |
          echo "${{ secrets.YOUTUBE_API_KEY }}" > api.txt
          echo "${{ secrets.CLIENT_SECRETS }}" > client_secrets.json