name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set working directory
        run: |
          mkdir -p /root/youtube-converter
          cp -r ./* /root/youtube-converter/
          cd /root/youtube-converter
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      - name: Create required directories
        working-directory: /root/youtube-converter
        run: |
          mkdir -p videos output temp cache/models logs
          chmod -R 777 videos output temp cache logs
      
      - name: Setup environment
        working-directory: /root/youtube-converter
        run: |
          echo "${{ secrets.YOUTUBE_API_KEY }}" > api.txt
          echo "${{ secrets.CLIENT_SECRETS }}" > client_secrets.json
      
      - name: Build and start containers
        working-directory: /root/youtube-converter
        run: |
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
      
      - name: Show container status
        working-directory: /root/youtube-converter
        run: |
          docker-compose ps
          docker-compose logs
      
      - name: Install systemd service
        working-directory: /root/youtube-converter
        run: |
          sudo cp systemd/youtube-converter.service /etc/systemd/system/
          sudo systemctl daemon-reload
          sudo systemctl enable youtube-converter
          sudo systemctl restart youtube-converter