name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.SSH_HOST }}
          
      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DEPLOY_PATH: /root/youtube-converter
        run: |
          # Проверяем и освобождаем порты если нужно
          ssh $SSH_USER@$SSH_HOST "sudo lsof -t -i:8080 | xargs -r kill -9"
          ssh $SSH_USER@$SSH_HOST "sudo lsof -t -i:9090 | xargs -r kill -9"
          
          ssh $SSH_USER@$SSH_HOST "mkdir -p $DEPLOY_PATH/{videos,output,temp,cache/models,logs}"
          scp -r ./* $SSH_USER@$SSH_HOST:$DEPLOY_PATH/
          ssh $SSH_USER@$SSH_HOST "cd $DEPLOY_PATH && \
            chmod -R 777 videos output temp cache logs && \
            docker-compose down --volumes && \
            docker system prune -af --volumes && \
            docker-compose up -d --build"

      - name: Health check
        run: |
          sleep 30
          curl -f "http://${{ secrets.SSH_HOST }}:8080/health" || exit 1