version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app/src
    volumes:
      - ./output:/app/output
      - ./cache:/app/cache
      - ./torch:/app/torch
      - ./config:/app/config
    command: gunicorn --bind 0.0.0.0:8080 --workers 1 --timeout 2000 --limit-request-line 8190 --limit-request-field_size 0 main:app
    deploy:
      resources:
        limits:
          memory: 500MB  # Ограничиваем Flask до 500MB
    depends_on:
      - redis
    restart: unless-stopped

  celery:
    build: .
    command: celery -A celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./output:/app/output
      - ./cache:/app/cache
      - ./torch:/app/torch
      - ./config:/app/config
    deploy:
      resources:
        limits:
          memory: 250MB  # Ограничиваем Celery до 250MB
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
